apiVersion: v2
name: unikorn-stack
description: A Helm chart for deploying Unikorn Cloud.

type: application

version: v0.1.2
appVersion: v0.1.2

icon: https://raw.githubusercontent.com/unikorn-cloud/assets/main/images/logos/dark-on-light/icon.png

dependencies:
- name: core
  version: v0.1.49
  repository: https://unikorn-cloud.github.io/core
- name: unikorn-identity
  version: v0.2.13
  repository: https://unikorn-cloud.github.io/identity
- name: unikorn-region
  version: v0.1.13
  repository: https://unikorn-cloud.github.io/region
- name: unikorn-kubernetes
  version: v0.2.16
  repository: https://unikorn-cloud.github.io/kubernetes
- name: unikorn-ui
  version: v0.2.5
  repository: https://unikorn-cloud.github.io/ui
