name: Release
on:
  push:
    branches:
    - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Install Helm
      uses: azure/setup-helm@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Add Repos
      run: |
        helm repo add unikorn-core https://unikorn-cloud.github.io/core
        helm repo add unikorn-identity https://unikorn-cloud.github.io/identity
        helm repo add unikorn-region https://unikorn-cloud.github.io/region
        helm repo add unikorn-kubernetes https://unikorn-cloud.github.io/kubernetes
        helm repo add unikorn-ui https://unikorn-cloud.github.io/ui
    - name: Release
      uses: helm/chart-releaser-action@v1.4.1
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CR_SKIP_EXISTING: 'true'
